import { NextResponse } from "next/server";
import { z } from "zod";
import { requireParentApi } from "@/lib/auth/require-parent";
import { createClient } from "@/lib/supabase/server";

export async function GET(request: Request) {
  try {
    await requireParentApi();
    const url = new URL(request.url);
    const parsed = z.object({ familyId: z.uuid(), from: z.iso.date(), to: z.iso.date() }).safeParse(Object.fromEntries(url.searchParams));
    if (!parsed.success) return NextResponse.json({ error: "Choose a valid export range." }, { status: 400 });
    const supabase = await createClient();
    const [{ data: family }, { data: students }, { data: evidence }, { data: observations }, { data: plans }] = await Promise.all([
      supabase.from("families").select("name").eq("id", parsed.data.familyId).single(),
      supabase.from("students").select("id, display_name, grade_band").eq("family_id", parsed.data.familyId),
      supabase.from("evidence_items").select("id, kind, title, raw_text, source_at").eq("family_id", parsed.data.familyId).gte("source_at", `${parsed.data.from}T00:00:00Z`).lte("source_at", `${parsed.data.to}T23:59:59Z`).order("source_at"),
      supabase.from("skill_observations").select("student_id, subject, skill_label, status, rationale, created_at").eq("family_id", parsed.data.familyId).eq("approval_status", "approved"),
      supabase.from("artifacts").select("title, summary, content, created_at").eq("family_id", parsed.data.familyId).eq("type", "weekly_plan").eq("status", "approved"),
    ]);
    if (!family) return NextResponse.json({ error: "Workspace not found." }, { status: 404 });
    const payload = { title: `${family.name} · Klio portfolio`, range: parsed.data, generatedAt: new Date().toISOString(), students, evidence, approvedObservations: observations, approvedPlans: plans, notice: "Generated by Klio for parent review." };
    return new NextResponse(JSON.stringify(payload, null, 2), {
      headers: { "content-type": "application/json; charset=utf-8", "content-disposition": `attachment; filename="klio-portfolio-${parsed.data.from}-${parsed.data.to}.json"`, "cache-control": "private, no-store" },
    });
  } catch { return NextResponse.json({ error: "Sign in to export." }, { status: 401 }); }
}
